### PR TITLE
Added badge SVG customization URL query params and associated tests

### PR DESCRIPTION
**Pull request by erjdev**
Per issue #402 , it seemed like a quick win to add some url params for different badge settings

### CODE REVIEW

**Review by boyter — APPROVED** [review]

**Comment by boyter** [comment]
Neat. Cheers. Ill yeet it into production now.

**Comment by boyter** [comment]
Right deployed. Should be all good. Please give it a test and let me know how it goes for you! Ideally with some examples here too. Ill have to update the README.md to ensure people know how to do it as well.

**Comment by boyter** [comment]
Updated README.md with details for this as well.

Thanks so much for taking the time out to do this.

**Comment by erjdev** [comment]
No worries at all - appreciate the code analysis.  It fulfilled a need I had, and it seems like it's well maintained and documented.

Glad to contribute, and I hope I can find the time to do so in the future.

**Comment by boyter** [comment]
Yes it won't work with private repositories, but then again the source code is there if someone wants to get it working or set it up for their own use.

**Pull request merged**
