### PR TITLE
Added support for remapping extensions

### PR DESCRIPTION
**Pull request by davidribyrne**
Added a --RemapExtensions option that allows users to force extensions to be mapped to a specific language.

### CODE REVIEW

**Comment by boyter** [comment]
I may be missing something here, but how is this different to the currently implemented

```
--count-as string             count extension as language [e.g. jsp:htm,chead:"C Header" maps extension jsp to html and chead to C Header]
```

There is probably something I am missing here that you are aware of.

**Comment by davidribyrne** [comment]
🤯 Well, that's embarrassing; I don't know how I missed that flag. On the positive side, I became more familiar with Go and with your code (which is well organized). Thank you for your nice work.

**Comment by davidribyrne** [comment]
Thank you for the fast response too

**Comment by boyter** [comment]
Hah no hard feelings at all. I thought maybe there was something I was missing. Glad you liked the code and I do appreciate the submission.

I wonder if I could change the README to make this functionality more obvious somehow to avoid people missing it such as yourself.

**Pull request closed without merging**
